# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-28T10:53:35"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["main"]
__private__ = []
__deps__ = []
point = (10, 20)
def main():
    global point
    _match_subject_1 = point
    if isinstance(_match_subject_1, (list, tuple)) and len(_match_subject_1) == 2 and True and _match_subject_1[1] == 0:
        x = _match_subject_1[0]
        print(x)
    elif True:
        print(0)
    return 0