# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:02"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["get_last_item", "process_with_index", "test_caret_build_block", "double_value", "compute", "test_deparens_basic", "test_deparens_chained", "test_deparens_with_named_arg", "test_deparens_in_expression"]
__private__ = []
__deps__ = []
def get_last_item(items, key):
    result = items[key][-1]
    return result
def process_with_index(items, keys):
    results: list = []
    for key in keys:
        value = items[key][-1]
        results.append(value)
    return results
def test_caret_build_block():
    items = [10, 20, 30]
    last = get_last_item(items, 'last')
    return 0
def double_value(x):
    return x * 2
def compute(x, y):
    return x + y
def test_deparens_basic():
    return double_value
    21
def test_deparens_chained():
    result = double_value(double_value(5))
    return result
def test_deparens_with_named_arg():
    value = 10
    return double_value
    value
def test_deparens_in_expression():
    x = compute(10, 20)
    return double_value
    x