# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:02"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["Point2D", "Rect", "create_point_kw", "create_point_pos", "area_of", "Status", "describe"]
__private__ = []
__deps__ = []
cdef struct Point2D:
    int x
    int y
cdef struct Rect:
    double width
    double height
def create_point_kw(x, y):
    return Point2D(x=x, y=y)
def create_point_pos(x, y):
    return Point2D(x, y)
def area_of(rect):
    return rect.width * rect.height
from enum import IntEnum, auto
class Status(IntEnum):
    PENDING = 'pending'
    COMPLETED = 'completed'
    FAILED = 'failed'
def describe(status):
    return str(status.value)