# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:03"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["main"]
__private__ = []
__deps__ = []
def main():
    a: int = 42
    b: double = 3.14
    c: double = 2.71828
    d: bool = True
    print(f'int: {a}')
    print(f'float: {b}')
    print(f'double: {c}')
    print(f'bool: {d}')
    e: double = <double>a
    f: bool = True
    print(f'auto(int to float): {e}')
    print(f'bool: {f}')
    name: str = 'Cypy'
    greeting: str = f'Hello, {name}!'
    raw_str: str = 'Raw\nstring'
    print(greeting)
    print(raw_str)
    numbers: list = [1, 2, 3, 4, 5]
    print(f'list<int>: {numbers}')
    point: tuple = (10, 20)
    data: tuple = ('test', 42, 3.14)
    print(f'point: {point}')
    print(f'data: {data}')
    inferred = 42
    print(f'inferred type: {type(inferred)}')
    return 0
if __name__ == '__main__':
    main()