# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:04"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["fetch_data", "run_concurrent", "main"]
__private__ = []
__deps__ = ["asyncio"]
import asyncio
async def fetch_data(url):
    print(f'Fetching {url}...')
    await asyncio.sleep(1)
    return f'Data from {url}'
async def run_concurrent():
    print('=== go 关键字 (协程) ===')
    task1 = asyncio.create_task(fetch_data('https://api.example.com/data1'))
    task2 = asyncio.create_task(fetch_data('https://api.example.com/data2'))
    result1 = await task1
    result2 = await task2
    print(f'Result 1: {result1}')
    print(f'Result 2: {result2}')
def main():
    asyncio.run(run_concurrent())
    return 0
if __name__ == '__main__':
    main()