# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:05"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["clamp", "total", "echo", "main"]
__private__ = []
__deps__ = []
# constraint Numeric = int | float | double
# constraint Wide = Numeric | str
def clamp(v, lo, hi):
    if v < lo:
        return lo
    if v > hi:
        return hi
    return v
def total(a, b):
    return a + b
def echo(v):
    return v
def main():
    print(clamp(5, 1, 10))
    print(clamp(2.5, 1.0, 1.5))
    print(total(20, 22))
    print(total(0.5, 0.25))
    print(echo('flattened'))
    print(echo(7))
    return 0