# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:05"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["main"]
__private__ = []
__deps__ = []
def main():
    score: int = 85
    if score >= 90:
        print('Excellent!')
    else:
        if score >= 80:
            print('Good!')
        else:
            if score >= 60:
                print('Pass!')
            else:
                print('Fail!')
    print('\nFor loop:')
    for i in range(5):
        print(f'  i = {i}')
    print('\nFor loop with step:')
    for i in range(0, 10, 2):
        print(f'  i = {i}')
    fruits: list = ['apple', 'banana', 'cherry']
    print('\nList iteration:')
    for fruit in fruits:
        print(f'  fruit: {fruit}')
    print('\nWhile loop:')
    count: int = 0
    while count < 5:
        print(f'  count = {count}')
        count = count + 1
    print('\nBreak and continue:')
    for i in range(10):
        if i == 3:
            continue
        if i == 7:
            break
        print(f'  i = {i}')
    print('\nMatch statement:')
    x: int = 2
    _match_subject_1 = x
    if _match_subject_1 == 1:
        print('One')
    elif _match_subject_1 == 2:
        print('Two')
    elif _match_subject_1 == 3:
        print('Three')
    elif True:
        print('Other')
    return 0
if __name__ == '__main__':
    main()