# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:08"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["identity", "wrap_in_list", "Box", "generic_usage", "type_inference"]
__private__ = []
__deps__ = []
def identity(value):
    ''
    '返回传入的值'
    ''
    return value
def wrap_in_list(value):
    ''
    '将值包装在列表中'
    ''
    return [value]
cdef class Box:
    __slots__ = ("value",)
    cdef public object value
    @cython.final
    def __init__(self, value):
        self.value = value
    @cython.binding(False)
    def get(self):
        return self.value
    @cython.binding(False)
    def set(self, new_value):
        self.value = new_value
def generic_usage():
    int_result = (int(), identity(42))[1]
    str_result = (str(), identity('hello'))[1]
    print(f'int identity: {int_result}')
    print(f'str identity: {str_result}')
    int_list = (int(), wrap_in_list(10))[1]
    print(f'int list: {int_list}')
    int_box = (int(), Box(value=100))[1]
    print(f'box value: {int_box.get()}')
    int_box.set(200)
    print(f'updated box: {int_box.get()}')
def type_inference():
    inferred = identity(3.14)
    print(f'推断类型: {inferred}')
    numbers = [1, 2, 3]
    print(f'列表类型推断: {numbers}')
generic_usage()
print('-' * 30)
type_inference()