# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:09"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["main"]
__private__ = []
__deps__ = []
def main():
    print('=== 基本列表推导式 ===')
    squares = [x ** 2 for x in range(10)]
    print(f'Squares: {squares}')
    print('\n=== 带条件的列表推导式 ===')
    even_squares = [x ** 2 for x in range(10) if x % 2 == 0]
    print(f'Even squares: {even_squares}')
    print('\n=== 嵌套循环 ===')
    pairs = [(x, y) for x in [1, 2, 3] for y in [4, 5, 6]]
    print(f'Pairs: {pairs}')
    return 0
if __name__ == '__main__':
    main()