# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:10"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["Status", "Document", "Report", "process_document"]
__private__ = []
__deps__ = []
from enum import IntEnum, auto
class Status(IntEnum):
    PENDING = auto()
    PROCESSING = auto()
    COMPLETED = auto()
    ERROR = auto()
class Document:
    def __init__(self, title):
        self.title = title
    def print(self):
        print(f'Document: {self.title}')
class Report(Document):
    def __init__(self, title, pages):
        Document.__init__(self, title)
        self.pages = pages
    def print(self):
        print(f'Report: {self.title} ({self.pages} pages)')
def process_document(doc):
    doc.print()
doc = Document('Meeting Notes')
report = Report('Quarterly Report', 42)
process_document(doc)
process_document(report)