# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:11"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["use_constants", "debug_log"]
__private__ = []
__deps__ = []
MAX_SIZE = 100
PI = 3.141592653589793
def use_constants():
    global PI
    print(f'MAX_SIZE = {MAX_SIZE}')
    print(f'PI = {PI}')
    circumference = 2 * PI * 5
    print(f'半径为5的圆周长: {circumference}')
DEBUG = True
def debug_log(message):
    global DEBUG
    if DEBUG:
        print(f'[DEBUG] {message}')
use_constants()
print('-' * 30)
debug_log('这是一条调试消息')