# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:13"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["make_point", "test_named_param_sugar", "add_values", "test_mixed_named_params", "test_guard_in_for_loop", "test_guard_in_while_loop", "test_guard_not_in_loop", "test_guard_single_line_else", "test_guard_in_nested_loop", "test_guard_multiple_in_loop", "main"]
__private__ = []
__deps__ = []
def make_point(x, y, z):
    return (x, y, z)
def test_named_param_sugar():
    x = 1.0
    y = 2.0
    z = 3.0
    return make_point(x=x, y=y, z=z)
def add_values(a, b, c):
    return a + b + c
def test_mixed_named_params():
    x = 10
    y = 20
    c = 30
    return add_values(x, y, c=c)
def test_guard_in_for_loop():
    count: int = 0
    for i in range(10):
        if not (i < 5):
            break
        count = count + 1
    return count
def test_guard_in_while_loop():
    count: int = 0
    i: int = 0
    while i < 10:
        if not (i < 3):
            break
        count = count + 1
        i = i + 1
    return count
def test_guard_not_in_loop():
    x: int = 0
    if not (x > 0):
        return 'invalid input'
    return 'ok'
def test_guard_single_line_else():
    value: int = -1
    if not (value >= 0):
        return 'negative'
    return 'positive'
def test_guard_in_nested_loop():
    total: int = 0
    for i in range(5):
        for j in range(5):
            if not (i + j < 8):
                break
            total = total + 1
    return total
def test_guard_multiple_in_loop():
    count: int = 0
    for i in range(20):
        if not (i % 2 == 0):
            continue
        if not (i < 10):
            break
        count = count + 1
    return count
def main():
    print('=== Cypy 新语法特性测试 ===')
    point = test_named_param_sugar()
    print(f'1. name~ 语法糖: {point}')
    mixed = test_mixed_named_params()
    print(f'2. 混合命名参数: {mixed}')
    guard_result1 = test_guard_in_for_loop()
    print(f'3. for 循环 guard: {guard_result1}')
    guard_result2 = test_guard_in_while_loop()
    print(f'4. while 循环 guard: {guard_result2}')
    guard_result3 = test_guard_not_in_loop()
    print(f'5. 非循环 guard: {guard_result3}')
    guard_result4 = test_guard_single_line_else()
    print(f'6. 单行 else 分支 guard: {guard_result4}')
    guard_result5 = test_guard_in_nested_loop()
    print(f'7. 嵌套循环 guard: {guard_result5}')
    guard_result6 = test_guard_multiple_in_loop()
    print(f'8. 多重 guard: {guard_result6}')
    print('=== 8 个用例全部调用完毕 ===')
    return 0
if __name__ == '__main__':
    main()