# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:14"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["add_one", "multiply_by_two", "square", "basic_pipeline", "filter_even", "sum_list", "list_pipeline"]
__private__ = []
__deps__ = []
def add_one(x):
    return x + 1
def multiply_by_two(x):
    return x * 2
def square(x):
    return x ** 2
def basic_pipeline():
    result1 = square(multiply_by_two(add_one(5)))
    print(f'传统方式: {result1}')
    result2 = square(multiply_by_two(add_one(5)))
    print(f'管道方式: {result2}')
def filter_even(items):
    result = []
    for n in items:
        if n % 2 == 0:
            result.append(n)
    return result
def sum_list(items):
    total = 0
    for n in items:
        total = total + n
    return total
def list_pipeline():
    numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    total = sum_list(filter_even(numbers))
    print(f'偶数之和: {total}')
basic_pipeline()
print('-' * 30)
list_pipeline()