# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:14"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["pointer_concepts", "Vector", "struct_example"]
__private__ = []
__deps__ = []
def pointer_concepts():
    x = 10
    print(f'变量 x 的值: {x}')
    print('指针操作演示完成')
cdef struct Vector:
    double x
    double y
    double z
def struct_example():
    v = Vector(x=1.0, y=2.0, z=3.0)
    print(f'向量: ({v.x}, {v.y}, {v.z})')
    v.x = 10.0
    print(f'修改后: ({v.x}, {v.y}, {v.z})')
pointer_concepts()
print('-' * 30)
struct_example()