# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:16"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["Point", "Rectangle", "create_point", "calculate_area", "main"]
__private__ = []
__deps__ = []
cdef class Point:
    __slots__ = ("x", "y")
    cdef public int x
    cdef public int y
    @cython.binding(False)
    def __init__(self, x, y):
        self.x = x
        self.y = y
cdef class Rectangle:
    __slots__ = ("width", "height")
    cdef public double width
    cdef public double height
    @cython.binding(False)
    def __init__(self, width, height):
        self.width = width
        self.height = height
def create_point(x, y):
    return Point(x=x, y=y)
def calculate_area(rect):
    return rect.width * rect.height
def main():
    p = create_point(10, 20)
    print(f'point = ({p.x}, {p.y})')
    rect = Rectangle(width=5.0, height=3.0)
    print(f'rect = {rect.width} x {rect.height}')
    area = calculate_area(rect)
    print(f'area = {area}')
    return 0
if __name__ == '__main__':
    main()