# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:15"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["Point", "Rectangle", "Circle", "Color", "get_color_name", "main"]
__private__ = []
__deps__ = []
cdef class Point:
    __slots__ = ("x", "y")
    cdef public int x
    cdef public int y
    @cython.binding(False)
    def __init__(self, x, y):
        self.x = x
        self.y = y
    @cython.binding(False)
    def __add__(self, other):
        return Point(x=self.x + other.x, y=self.y + other.y)
    @cython.binding(False)
    def __str__(self):
        return f'({self.x}, {self.y})'
cdef class Rectangle:
    __slots__ = ("origin", "width", "height")
    cdef public Point origin
    cdef public int width
    cdef public int height
    @cython.final
    def __init__(self, origin, width, height):
        self.origin = origin
        self.width = width
        self.height = height
    @cython.binding(False)
    def area(self):
        return self.width * self.height
cdef class Circle:
    __slots__ = ("center", "radius")
    cdef public Point center
    cdef public double radius
    @cython.final
    def __init__(self, center, radius):
        self.center = center
        self.radius = radius
    @cython.binding(False)
    def circumference(self):
        return 2 * 3.14159 * self.radius
    @cython.binding(False)
    def contains(self, point):
        dx: double = point.x - self.center.x
        dy: double = point.y - self.center.y
        dist_sq: double = dx ** 2 + dy ** 2
        radius_sq: double = self.radius ** 2
        return bool(dist_sq <= radius_sq)
from enum import IntEnum, auto
class Color(IntEnum):
    RED = 1
    GREEN = 2
    BLUE = 3
def get_color_name(color):
    _match_subject_1 = color
    if _match_subject_1 == Color.RED:
        return 'Red'
    elif _match_subject_1 == Color.GREEN:
        return 'Green'
    elif _match_subject_1 == Color.BLUE:
        return 'Blue'
def main():
    p1: Point = Point(x=1, y=2)
    p2: Point = Point(x=3, y=4)
    p3: Point = p1 + p2
    print(f'p1: {p1}')
    print(f'p2: {p2}')
    print(f'p1 + p2: {p3}')
    rect: Rectangle = Rectangle(origin=Point(x=0, y=0), width=10, height=5)
    print(f'Rectangle area: {rect.area()}')
    c: object = Color.RED
    print(f'Color: {c}')
    print(f'Color value: {c.value}')
    print(f'Color name: {get_color_name(Color.GREEN)}')
    immutable_point: Point = Point(x=10, y=20)
    print(f'Immutable point: {immutable_point}')
    mutable_point: Point = Point(x=5, y=5)
    mutable_point.x = 15
    print(f'Mutable point after update: {mutable_point}')
    circle: Circle = Circle(center=Point(x=0, y=0), radius=5)
    print(f'Circumference: {circle.circumference()}')
    print(f'Contains (3, 4): {circle.contains(Point(x=3, y=4))}')
    print(f'Contains (6, 0): {circle.contains(Point(x=6, y=0))}')
    return 0
if __name__ == '__main__':
    main()