# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:17"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["area", "km_per", "raw_meters", "show", "main"]
__private__ = []
__deps__ = []
def area(side):
    return side * side
def km_per(m):
    return <double>m / 1000.0
def raw_meters(k):
    return k * 1000.0
# constraint Length = float | float
def show(v):
    return v
def main():
    m: double = 2.5
    c: double = 0.04
    id1: int = 42
    print(area(m))
    print(area(c))
    print(id1 + 8)
    km: double = 1.5
    raw: double = raw_meters(km)
    print(raw)
    back: double = <double>raw
    print(back)
    print(km_per(2500.0))
    print(show(m))
    print(show(km))
    print(<double>m / <double>1000.0)
    return 0