# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:24"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["double_it", "process", "vec_sum", "main"]
__private__ = []
__deps__ = []
# === Meta Block ===
_duck_registry = {}
# Duck constraint: ValidNum
#   Operator: +(a, b) -> Self
_duck_registry['ValidNum'] = {'type_params': [], 'requirements': [{'kind': 'operator', 'name': '+', 'params': ['a', 'b'], 'return_type': 'Self', 'generic_args': [], 'is_unary': False}]}
# macro double_it - compile-time macro
def _macro_double_it(ts):
    # Macro body evaluated at compile time
    pass  # Macro expansion happens during parsing
def process(x):
    return x
def vec_sum(v):
    total = 0
    for x in v:
        total = total + x
    return total
def main():
    numbers = [1, 2, 3, 4, 5]
    s = vec_sum(numbers)
    print(f'vec sum = {s}')
    val: object = 42
    result = process(val)
    print(f'union passthrough = {result}')
    zeros = [0] * 10
    print(f'vec repeat len = {len(zeros)}')
    return 0
if __name__ == '__main__':
    main()