# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:25"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["process_value", "test_union", "main"]
__private__ = []
__deps__ = []
def process_value(x):
    return x
def test_union():
    x: object = 42
    y: object = 'hello'
    return len(str(x)) + len(str(y))
def main():
    print(f'union int passthrough = {process_value(42)}')
    print(f"union str passthrough = {process_value('hello')}")
    print(f'union test width = {test_union()}')
    return 0
if __name__ == '__main__':
    main()