# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:26"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["vec_sum", "test_vec_literal", "test_vec_repeat", "main"]
__private__ = []
__deps__ = []
def vec_sum(v):
    total = 0
    for x in v:
        total = total + x
    return total
def test_vec_literal():
    v = [1, 2, 3, 4]
    return vec_sum(v)
def test_vec_repeat():
    v = [0] * 5
    return len(v)
def main():
    print(f'vec literal sum = {test_vec_literal()}')
    print(f'vec repeat len = {test_vec_repeat()}')
    return 0
if __name__ == '__main__':
    main()