# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:22"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["combine", "main"]
__private__ = []
__deps__ = []
# === Meta Block ===
_duck_registry = {}
# Duck constraint: NumberLike
#   Operator: +(a, b) -> Self
_duck_registry['NumberLike'] = {'type_params': [], 'requirements': [{'kind': 'operator', 'name': '+', 'params': ['a', 'b'], 'return_type': 'Self', 'generic_args': [], 'is_unary': False}]}
def combine(a, b):
    return a + b
def main():
    print(f'meta duck combine int = {combine(20, 22)}')
    print(f'meta duck combine float = {combine(1.5, 2.25)}')
    return 0
if __name__ == '__main__':
    main()