# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-27T16:50:18"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["sort", "find_max", "add_values", "display", "process_container", "Widget", "main"]
__private__ = []
__deps__ = []
# === Meta Block ===
_duck_registry = {}
# Duck constraint: Comparable
#   Operator: <(a, b) -> bool
#   Operator: >(a, b) -> bool
#   Operator: <=(a, b) -> bool
#   Operator: >=(a, b) -> bool
#   Operator: ==(a, b) -> bool
#   Operator: !=(a, b) -> bool
_duck_registry['Comparable'] = {'type_params': [], 'requirements': [{'kind': 'operator', 'name': '<', 'params': ['a', 'b'], 'return_type': 'bool', 'generic_args': [], 'is_unary': False}, {'kind': 'operator', 'name': '>', 'params': ['a', 'b'], 'return_type': 'bool', 'generic_args': [], 'is_unary': False}, {'kind': 'operator', 'name': '<=', 'params': ['a', 'b'], 'return_type': 'bool', 'generic_args': [], 'is_unary': False}, {'kind': 'operator', 'name': '>=', 'params': ['a', 'b'], 'return_type': 'bool', 'generic_args': [], 'is_unary': False}, {'kind': 'operator', 'name': '==', 'params': ['a', 'b'], 'return_type': 'bool', 'generic_args': [], 'is_unary': False}, {'kind': 'operator', 'name': '!=', 'params': ['a', 'b'], 'return_type': 'bool', 'generic_args': [], 'is_unary': False}]}
# Duck constraint: Numeric
#   Operator: +(a, b) -> Self
#   Operator: -(a, b) -> Self
#   Operator: *(a, b) -> Self
#   Operator: /(a, b) -> Self
#   Operator: -a -> Self
_duck_registry['Numeric'] = {'type_params': [], 'requirements': [{'kind': 'operator', 'name': '+', 'params': ['a', 'b'], 'return_type': 'Self', 'generic_args': [], 'is_unary': False}, {'kind': 'operator', 'name': '-', 'params': ['a', 'b'], 'return_type': 'Self', 'generic_args': [], 'is_unary': False}, {'kind': 'operator', 'name': '*', 'params': ['a', 'b'], 'return_type': 'Self', 'generic_args': [], 'is_unary': False}, {'kind': 'operator', 'name': '/', 'params': ['a', 'b'], 'return_type': 'Self', 'generic_args': [], 'is_unary': False}, {'kind': 'operator', 'name': '-', 'params': ['a'], 'return_type': 'Self', 'generic_args': [], 'is_unary': True}]}
# === Meta Block ===
_duck_registry = {}
# Duck constraint: Named
#   Attribute: name: str
_duck_registry['Named'] = {'type_params': [], 'requirements': [{'kind': 'attribute', 'name': 'name', 'params': [], 'return_type': 'str', 'generic_args': [], 'is_unary': False}]}
# Duck constraint: Sized
#   Attribute: size: int
_duck_registry['Sized'] = {'type_params': [], 'requirements': [{'kind': 'attribute', 'name': 'size', 'params': [], 'return_type': 'int', 'generic_args': [], 'is_unary': False}]}
# Duck constraint: Identified
#   Attribute: id: int
#   Attribute: name: str
_duck_registry['Identified'] = {'type_params': [], 'requirements': [{'kind': 'attribute', 'name': 'id', 'params': [], 'return_type': 'int', 'generic_args': [], 'is_unary': False}, {'kind': 'attribute', 'name': 'name', 'params': [], 'return_type': 'str', 'generic_args': [], 'is_unary': False}]}
# === Meta Block ===
_duck_registry = {}
# Duck constraint: Iterable
#   Method: __iter__(self) -> Iterator
_duck_registry['Iterable'] = {'type_params': [], 'requirements': [{'kind': 'method', 'name': '__iter__', 'params': ['self'], 'return_type': 'Iterator', 'generic_args': [], 'is_unary': False}]}
# Duck constraint: Container
#   Generic: <T>
#   Method: add(self, item) -> None
#   Method: remove(self, item) -> bool
#   Method: __contains__(self, item) -> bool
#   Method: __len__(self) -> int
_duck_registry['Container'] = {'type_params': ['T'], 'requirements': [{'kind': 'method', 'name': 'add', 'params': ['self', 'item'], 'return_type': 'None', 'generic_args': [], 'is_unary': False}, {'kind': 'method', 'name': 'remove', 'params': ['self', 'item'], 'return_type': 'bool', 'generic_args': [], 'is_unary': False}, {'kind': 'method', 'name': '__contains__', 'params': ['self', 'item'], 'return_type': 'bool', 'generic_args': [], 'is_unary': False}, {'kind': 'method', 'name': '__len__', 'params': ['self'], 'return_type': 'int', 'generic_args': [], 'is_unary': False}]}
# Duck constraint: Indexable
#   Generic: <T>
#   Method: __getitem__(self, index) -> T
#   Method: __setitem__(self, index, value) -> None
_duck_registry['Indexable'] = {'type_params': ['T'], 'requirements': [{'kind': 'method', 'name': '__getitem__', 'params': ['self', 'index'], 'return_type': 'T', 'generic_args': [], 'is_unary': False}, {'kind': 'method', 'name': '__setitem__', 'params': ['self', 'index', 'value'], 'return_type': 'None', 'generic_args': [], 'is_unary': False}]}
# === Meta Block ===
_duck_registry = {}
# Duck constraint: Ordered
#   Reference: Comparable
#   Operator: <=>(a, b) -> int
_duck_registry['Ordered'] = {'type_params': [], 'requirements': [{'kind': 'reference', 'name': 'Comparable', 'params': [], 'return_type': None, 'generic_args': [], 'is_unary': False}, {'kind': 'operator', 'name': '<=>', 'params': ['a', 'b'], 'return_type': 'int', 'generic_args': [], 'is_unary': False}]}
# Duck constraint: SortableContainer
#   Generic: <T>
#   Reference: Comparable
#   Reference: Container<T>
_duck_registry['SortableContainer'] = {'type_params': ['T'], 'requirements': [{'kind': 'reference', 'name': 'Comparable', 'params': [], 'return_type': None, 'generic_args': [], 'is_unary': False}, {'kind': 'reference', 'name': 'Container', 'params': [], 'return_type': None, 'generic_args': ['T'], 'is_unary': False}]}
def sort(items):
    ''
    '对可比较的列表进行排序'
    ''
    return items
def find_max(a, b):
    ''
    '返回较大的值'
    ''
    if a > b:
        return a
    return b
def add_values(a, b):
    ''
    '对数值类型求和'
    ''
    return a + b
def display(obj):
    ''
    '显示有 name 属性的对象'
    ''
    print(obj.name)
def process_container(container):
    ''
    '处理存储整数的容器'
    ''
    container.add(42)
cdef class Widget:
    __slots__ = ("name",)
    cdef public str name
    @cython.binding(False)
    def __init__(self, name):
        self.name = name
def main():
    print(f'duck Comparable find_max(3, 7) = {find_max(3, 7)}')
    print(f'duck Numeric add_values(2, 5) = {add_values(2, 5)}')
    print(f'duck Comparable sort passthrough = {sort([3, 1, 2])}')
    w = Widget(name='duck-named-widget')
    display(w)
    return 0
if __name__ == '__main__':
    main()