# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: .fist-loop-20260927/hunts/adv_10_slice_step_zero.cypy
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = 'adv_10_slice_step_zero'
__file__ = '.fist-loop-20260927/hunts/adv_10_slice_step_zero.cypy'
__package__ = ''
__path__ = None
__compile_time__ = "2026-09-29T11:17:09"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["main"]
__private__ = []
__deps__ = []
def main():
    xs: Constant(line=2, col=9) = [1, 2, 3]
    ys = xs[0:3:0]
    return 0