from typing import Any, List
from cypyc.parser.parser import (
    ASTNode, Module, FuncDef, LetStmt, ReturnStmt, IfStmt, ForStmt, WhileStmt,
    BinOp, UnaryOp, Call, Name, Constant, Attribute, Subscript, StructDef,
    StructField, EnumDef, EnumVariant, DeferStmt, DerefExpr, PointerType,
    GenericType, TraitDef, ImplStmt, MetaBlock, GuardStmt, ComptimeStmt,
    BuildBlockExpr, CastExpr, ClassDef, Import, FromImport
)
from cypyc.codegen.type_mapper import TypeMapper


import os
import time
import platform

class CythonGenerator:
    def __init__(self, source_file: str = None):
        self.indent = 0
        self.output = []
        self.type_mapper = TypeMapper()
        self.in_cdef_context = False
        self.needs_libc_import = False  # 是否需要导入C标准库
        self.source_file = source_file  # 源文件路径
        # 模块符号收集
        self.public_symbols = []
        self.private_symbols = []
        self.imported_modules = []
        # 当前结构体名称（用于方法生成时添加self参数）
        self._current_struct_name = None

    def generate(self, node: ASTNode) -> str:
        self.output = []
        # 首先检测是否需要C库导入
        self._detect_libc_usage(node)
        self._visit(node)
        return "\n".join(self.output)
    
    def _detect_libc_usage(self, node: ASTNode) -> None:
        """检测代码中是否使用了需要C标准库的函数"""
        if isinstance(node, Call) and hasattr(node.func, 'id'):
            if node.func.id in ('malloc', 'free', 'sizeof', 'addr'):
                self.needs_libc_import = True
        for attr in dir(node):
            if not attr.startswith("_"):
                value = getattr(node, attr)
                if isinstance(value, ASTNode):
                    self._detect_libc_usage(value)
                elif isinstance(value, list):
                    for item in value:
                        if isinstance(item, ASTNode):
                            self._detect_libc_usage(item)
    
    def _check_is_generator(self, stmts: List[Any]) -> bool:
        """递归检查语句列表中是否包含 yield 语句"""
        for stmt in stmts:
            if hasattr(stmt, 'kind') and stmt.kind == 'YieldStmt':
                return True
            # 递归检查嵌套语句
            if hasattr(stmt, 'body') and isinstance(stmt.body, list):
                if self._check_is_generator(stmt.body):
                    return True
            # 检查 elif 和 else 分支
            if hasattr(stmt, 'orelse'):
                orelse = stmt.orelse
                if isinstance(orelse, list):
                    if self._check_is_generator(orelse):
                        return True
                elif hasattr(orelse, 'body') and isinstance(orelse.body, list):
                    if self._check_is_generator(orelse.body):
                        return True
        return False

    def _visit(self, node: ASTNode) -> None:
        method = f"_visit_{node.kind}"
        if hasattr(self, method):
            getattr(self, method)(node)
        else:
            self._visit_children(node)

    def _visit_children(self, node: ASTNode) -> None:
        for attr in dir(node):
            if not attr.startswith("_"):
                value = getattr(node, attr)
                if isinstance(value, ASTNode):
                    self._visit(value)
                elif isinstance(value, list):
                    for item in value:
                        if isinstance(item, ASTNode):
                            self._visit(item)

    def _write(self, text: str) -> None:
        if text:
            self.output.append("    " * self.indent + text)

    def _visit_Module(self, node: Module) -> None:
        self._write("# Generated by Cypy compiler")
        self._write("")
        
        # 添加C标准库导入
        if self.needs_libc_import:
            # sizeof是Cython内置关键字，不需要导入
            self._write("from libc.stdlib cimport malloc, free")
            self._write("")
        
        # 第一遍：收集模块信息
        self._collect_module_info(node)
        
        # 生成模块级魔法属性
        self._generate_module_magic_attrs()
        
        # 第二遍：生成代码
        for stmt in node.body:
            self._visit(stmt)
    
    def _collect_module_info(self, node: Module) -> None:
        """收集模块级符号和导入信息"""
        for stmt in node.body:
            if isinstance(stmt, FuncDef):
                name = stmt.name
                if name.startswith('_'):
                    self.private_symbols.append(name)
                else:
                    self.public_symbols.append(name)
            elif isinstance(stmt, StructDef):
                name = stmt.name
                if name.startswith('_'):
                    self.private_symbols.append(name)
                else:
                    self.public_symbols.append(name)
            elif isinstance(stmt, ClassDef):
                name = stmt.name
                if name.startswith('_'):
                    self.private_symbols.append(name)
                else:
                    self.public_symbols.append(name)
            elif isinstance(stmt, EnumDef):
                name = stmt.name
                if name.startswith('_'):
                    self.private_symbols.append(name)
                else:
                    self.public_symbols.append(name)
            elif isinstance(stmt, TraitDef):
                name = stmt.name
                if name.startswith('_'):
                    self.private_symbols.append(name)
                else:
                    self.public_symbols.append(name)
            elif isinstance(stmt, Import):
                module_name = stmt.module
                if module_name not in self.imported_modules:
                    self.imported_modules.append(module_name)
            elif isinstance(stmt, FromImport):
                module_name = stmt.module
                if module_name not in self.imported_modules:
                    self.imported_modules.append(module_name)
    
    def _generate_module_magic_attrs(self) -> None:
        """生成模块级魔法属性"""
        # 获取模块名（从文件名提取）
        module_name = "unknown"
        if self.source_file:
            module_name = os.path.splitext(os.path.basename(self.source_file))[0]
        
        # 文件路径
        file_path = self.source_file or ""
        
        # 包信息
        package_name = ""
        path_value = "None"
        if self.source_file:
            dir_name = os.path.dirname(self.source_file)
            init_file = os.path.join(dir_name, "__init__.py")
            if os.path.exists(init_file):
                package_name = os.path.basename(dir_name)
                path_value = f"['{dir_name}']"
        
        # 编译时间
        compile_time = time.strftime("%Y-%m-%dT%H:%M:%S")
        
        # 目标平台
        target_platform = f"{platform.machine()}-{platform.system().lower()}"
        
        # 生成魔法属性
        self._write(f"__name__ = \"{module_name}\"")
        self._write(f"__file__ = \"{file_path}\"")
        self._write(f"__package__ = \"{package_name}\"")
        self._write(f"__path__ = {path_value}")
        self._write(f"__compile_time__ = \"{compile_time}\"")
        self._write(f"__target__ = \"{target_platform}\"")
        self._write(f"__profile__ = \"debug\"")
        
        # __all__：公开API列表（不含_前缀，包含魔法方法）
        all_list = [s for s in self.public_symbols if not s.startswith('_') or (s.startswith('__') and s.endswith('__'))]
        all_str = ', '.join(f'"{s}"' for s in all_list)
        self._write(f"__all__ = [{all_str}]")
        
        # __private__：私有符号列表（_前缀）
        private_str = ', '.join(f'"{s}"' for s in self.private_symbols if s.startswith('_') and not (s.startswith('__') and s.endswith('__')))
        self._write(f"__private__ = [{private_str}]")
        
        # __deps__：依赖模块列表
        deps_str = ', '.join(f'"{s}"' for s in self.imported_modules)
        self._write(f"__deps__ = [{deps_str}]")
        
        self._write("")

    def _visit_Decorator(self, node: Any) -> None:
        """生成装饰器的 Cython 代码"""
        decorator_str = f"@{self._expr_to_str(node.name)}"
        if node.args:
            args_str = ", ".join(self._expr_to_str(arg) for arg in node.args)
            decorator_str += f"({args_str})"
        self._write(decorator_str)

    def _visit_FuncDef(self, node: FuncDef) -> None:
        # 生成装饰器
        if hasattr(node, 'decorators') and node.decorators:
            for decorator in node.decorators:
                self._visit_Decorator(decorator)
        
        has_type_annotation = any(p.type_annotation for p in node.params) or node.return_type
        
        # 处理 <checker> 参数检查站（定义时的 checker，在函数体开头自动调用）
        has_checker = node.params_checker is not None
        
        # 检查是否是结构体方法（如果是，需要添加 self 参数）
        is_struct_method = getattr(node, 'is_struct_method', False)
        
        # 检查方法是否已经有 self 参数
        has_self = node.params and node.params[0].name == 'self'
        
        # 检查是否是生成器函数（包含 yield 语句）
        # Cython 中 cpdef 函数不能包含 yield，必须使用 def
        is_generator = self._check_is_generator(node.body)
        
        if has_type_annotation and not is_generator:
            return_type = ""
            if node.return_type:
                return_type = f" {self._type_to_str(node.return_type)}"
            
            params = []
            # 结构体方法自动添加 self 参数（如果还没有）
            if is_struct_method and not has_self:
                params.append(f"{self._current_struct_name} self")
            
            # 定义时的 checker 不作为参数传递，而是在函数体开头自动调用
            # 调用时的 checker 会作为第一个参数传入（通过 Call.checker 字段）
            
            for param in node.params:
                param_str = param.name
                if param.type_annotation:
                    param_str = f"{self._type_to_str(param.type_annotation)} {param.name}"
                params.append(param_str)
            
            self._write(f"cpdef{return_type} {node.name}({', '.join(params)}):")
        else:
            params = []
            # 结构体方法自动添加 self 参数（如果还没有）
            if is_struct_method and not has_self:
                params.append("self")
            
            # 添加普通参数
            for param in node.params:
                params.append(param.name)
            
            params_str = ", ".join(params)
            if params_str:
                self._write(f"def {node.name}({params_str}):")
            else:
                self._write(f"def {node.name}():")
        
        self.indent += 1
        
        # 分离defer语句和普通语句
        defer_stmts = []
        normal_stmts = []
        
        for stmt in node.body:
            if isinstance(stmt, DeferStmt):
                defer_stmts.append(stmt)
            else:
                normal_stmts.append(stmt)
        
        # 在函数体开头添加 checker 调用（如果有）
        if has_checker and node.params_checker:
            checker_call = f"{node.params_checker}()"
            self._write(checker_call)
        
        # 检查是否有defer语句
        if defer_stmts:
            # 生成try块
            self._write("try:")
            self.indent += 1
            for stmt in normal_stmts:
                self._visit(stmt)
            self.indent -= 1
            
            # 生成finally块（defer语句按逆序执行）
            self._write("finally:")
            self.indent += 1
            # defer语句按声明顺序的逆序执行
            for defer_stmt in reversed(defer_stmts):
                for stmt in defer_stmt.body:
                    # defer body中可能包含表达式节点（如Call），需要转换为表达式语句
                    if isinstance(stmt, (Call, BinOp, UnaryOp, Name, Constant)):
                        self._write(self._expr_to_str(stmt))
                    else:
                        self._visit(stmt)
            self.indent -= 1
        else:
            # 没有defer语句，直接输出所有语句
            for stmt in node.body:
                self._visit(stmt)
        
        self.indent -= 1
        self._write("")

    def _visit_LetStmt(self, node: LetStmt) -> None:
        if node.type_annotation:
            cdef_type = self._type_to_str(node.type_annotation)
            if node.value:
                if isinstance(node.value, ComptimeStmt):
                    value = self._expr_to_str(node.value.expr)
                else:
                    value = self._expr_to_str(node.value)
                self._write(f"cdef {cdef_type} {node.name} = {value}")
            else:
                self._write(f"cdef {cdef_type} {node.name}")
        else:
            if node.value:
                if isinstance(node.value, ComptimeStmt):
                    value = self._expr_to_str(node.value.expr)
                else:
                    value = self._expr_to_str(node.value)
                self._write(f"{node.name} = {value}")
            else:
                self._write(f"{node.name}")

    def _visit_ReturnStmt(self, node: ReturnStmt) -> None:
        if node.value:
            self._write(f"return {self._expr_to_str(node.value)}")
        else:
            self._write("return")

    def _visit_IfStmt(self, node: IfStmt) -> None:
        self._write(f"if {self._expr_to_str(node.test)}:")
        self.indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self.indent -= 1
        if node.orelse:
            self._write("else:")
            self.indent += 1
            for stmt in node.orelse:
                self._visit(stmt)
            self.indent -= 1

    def _visit_ForStmt(self, node: ForStmt) -> None:
        self._write(f"for {self._expr_to_str(node.target)} in {self._expr_to_str(node.iter)}:")
        self.indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self.indent -= 1

    def _visit_WhileStmt(self, node: WhileStmt) -> None:
        self._write(f"while {self._expr_to_str(node.test)}:")
        self.indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self.indent -= 1

    def _visit_BreakStmt(self, node: Any) -> None:
        self._write("break")

    def _visit_ContinueStmt(self, node: Any) -> None:
        self._write("continue")

    def _visit_MatchStmt(self, node: Any) -> None:
        """生成 match/case 语句的 Cython 代码"""
        self._write(f"match {self._expr_to_str(node.subject)}:")
        self.indent += 1
        for case in node.cases:
            pattern_str = self._pattern_to_str(case.pattern)
            self._write(f"case {pattern_str}:")
            self.indent += 1
            for stmt in case.body:
                self._visit(stmt)
            self.indent -= 1
        if node.orelse:
            self._write("else:")
            self.indent += 1
            for stmt in node.orelse:
                self._visit(stmt)
            self.indent -= 1
        self.indent -= 1
    
    def _pattern_to_str(self, pattern: Any) -> str:
        """将模式转换为字符串表示"""
        if isinstance(pattern, list):
            # 元组或列表模式：(pattern1, pattern2) 或 [pattern1, pattern2]
            pattern_strs = []
            for p in pattern:
                pattern_strs.append(self._pattern_to_str(p))
            return f"({', '.join(pattern_strs)})"
        if isinstance(pattern, dict) and "or" in pattern:
            # OR 模式：pattern1 | pattern2
            pattern_strs = []
            for p in pattern["or"]:
                pattern_strs.append(self._pattern_to_str(p))
            return " | ".join(pattern_strs)
        if hasattr(pattern, 'kind') and pattern.kind == "Pattern":
            # 变量模式
            return pattern.name
        # 默认使用表达式转换
        return self._expr_to_str(pattern)

    def _visit_WithStmt(self, node: Any) -> None:
        """生成 with 语句的 Cython 代码"""
        items_str = []
        for item in node.items:
            expr = self._expr_to_str(item[0])
            if item[1]:
                items_str.append(f"{expr} as {item[1].id}")
            else:
                items_str.append(expr)
        self._write(f"with {', '.join(items_str)}:")
        self.indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self.indent -= 1

    def _visit_DelStmt(self, node: Any) -> None:
        """生成 del 语句的 Cython 代码"""
        targets_str = ", ".join(self._expr_to_str(target) for target in node.targets)
        self._write(f"del {targets_str}")

    def _visit_ExprStmt(self, node: Any) -> None:
        self._write(self._expr_to_str(node.value))

    def _visit_Assign(self, node: Any) -> None:
        target = self._expr_to_str(node.target)
        if isinstance(node.value, ComptimeStmt):
            # comptime 在编译时求值，结果作为常量
            value = self._expr_to_str(node.value.expr)
        else:
            value = self._expr_to_str(node.value)
        self._write(f"{target} = {value}")

    def _visit_StructDef(self, node: StructDef) -> None:
        # 如果结构体有方法，使用 cdef class，否则使用 cdef struct
        if hasattr(node, 'methods') and node.methods:
            # 设置当前结构体名称，用于方法生成时添加 self 参数
            self._current_struct_name = node.name
            self._write(f"cdef class {node.name}:")
            self.indent += 1
            # 生成字段 - cdef class 需要 cdef 前缀
            for field in node.fields:
                if isinstance(field, StructField):
                    field_type = self._type_to_str(field.type_annotation) if field.type_annotation else "object"
                    self._write(f"cdef {field_type} {field.name}")
            
            # 生成 __init__ 方法用于初始化字段
            init_params = []
            init_body = []
            for field in node.fields:
                if isinstance(field, StructField):
                    param_name = field.name
                    if field.default_value is not None:
                        init_params.append(f"{param_name}={self._expr_to_str(field.default_value)}")
                        init_body.append(f"self.{param_name} = {param_name}")
                    else:
                        init_params.append(param_name)
                        init_body.append(f"self.{param_name} = {param_name}")
            
            self._write(f"def __init__(self{', ' + ', '.join(init_params) if init_params else ''}):")
            self.indent += 1
            for line in init_body:
                self._write(line)
            self.indent -= 1
            
            # 生成方法 - 标记为结构体方法
            for method in node.methods:
                method.is_struct_method = True
                self._visit(method)
            self.indent -= 1
            # 清除当前结构体名称
            self._current_struct_name = None
        else:
            self._write(f"cdef struct {node.name}:")
            self.indent += 1
            # 生成字段 - cdef struct 不需要 cdef 前缀
            for field in node.fields:
                if isinstance(field, StructField):
                    field_type = self._type_to_str(field.type_annotation) if field.type_annotation else "object"
                    self._write(f"{field_type} {field.name}")
            self.indent -= 1
        self._write("")

    def _visit_StructField(self, node: StructField) -> None:
        """生成结构体字段的 Cython 代码"""
        field_type = self._type_to_str(node.type_annotation) if node.type_annotation else "object"
        if node.default_value is not None:
            self._write(f"{field_type} {node.name} = {self._expr_to_str(node.default_value)}")
        else:
            self._write(f"{field_type} {node.name}")

    def _visit_EnumDef(self, node: EnumDef) -> None:
        self._write("from enum import IntEnum")
        self._write("")
        self._write(f"class {node.name}(IntEnum):")
        self.indent += 1
        for variant in node.variants:
            if isinstance(variant, EnumVariant):
                if variant.value is not None:
                    self._write(f"{variant.name} = {self._expr_to_str(variant.value)}")
                else:
                    self._write(f"{variant.name}")
        self.indent -= 1
        self._write("")

    def _visit_EnumVariant(self, node: EnumVariant) -> None:
        """生成枚举变体的 Cython 代码"""
        if node.value is not None:
            self._write(f"{node.name} = {self._expr_to_str(node.value)}")
        else:
            self._write(f"{node.name}")

    def _visit_GuardStmt(self, node: GuardStmt) -> None:
        """生成 guard 语句的 Cython 代码"""
        if node.is_let:
            # guard let target = expr else value
            target = self._expr_to_str(node.let_target)
            value = self._expr_to_str(node.test)
            self._write(f"{target} = {value}")
            self._write(f"if not {target}:")
            self.indent += 1
            # orelse 可能是表达式或语句列表（多行形式）
            if isinstance(node.orelse, list):
                for stmt in node.orelse:
                    if hasattr(stmt, 'kind'):
                        self._visit(stmt)
            else:
                self._write(f"return {self._expr_to_str(node.orelse)}")
            self.indent -= 1
        else:
            # guard cond else value
            test = self._expr_to_str(node.test)
            self._write(f"if not ({test}):")
            self.indent += 1
            # orelse 可能是表达式或语句列表（多行形式）
            if isinstance(node.orelse, list):
                for stmt in node.orelse:
                    if hasattr(stmt, 'kind'):
                        self._visit(stmt)
            else:
                self._write(f"return {self._expr_to_str(node.orelse)}")
            self.indent -= 1

    def _visit_ComptimeStmt(self, node: ComptimeStmt) -> None:
        """生成 comptime 语句的 Cython 代码"""
        # comptime 在编译时求值，结果作为常量
        self._write(f"# comptime: {self._expr_to_str(node.expr)}")

    def _visit_BuildBlockExpr(self, node: BuildBlockExpr) -> None:
        """生成构建块表达式的 Cython 代码"""
        if node.block_type == BuildBlockExpr.BUILD_ASSIGN:
            # =: 变量构建块，最后表达式作为返回值
            self._write("(")
            self._write("lambda: (")
            self.indent += 1
            for stmt in node.body:
                stmt_kind = getattr(stmt, 'kind', None)
                if stmt_kind == 'ReturnStmt':
                    # return 语句直接生成
                    self._visit(stmt)
                elif isinstance(stmt, (BinOp, UnaryOp, Call, Name, Constant)):
                    self._write(self._expr_to_str(stmt) + ",")
                else:
                    # 其他语句正常访问
                    self._visit(stmt)
            self.indent -= 1
            self._write(")[-1]")
            self._write(")()")
        elif node.block_type == BuildBlockExpr.BUILD_CALL:
            # ~: 调用构建块，生成无参函数并立即调用
            self._write("(")
            self._write("lambda: (")
            self.indent += 1
            for stmt in node.body:
                stmt_kind = getattr(stmt, 'kind', None)
                if stmt_kind == 'ReturnStmt':
                    # return 语句直接生成
                    self._visit(stmt)
                elif isinstance(stmt, (BinOp, UnaryOp, Call, Name, Constant)):
                    self._write(self._expr_to_str(stmt) + ",")
                else:
                    self._visit(stmt)
            self.indent -= 1
            self._write(")[-1]")
            self._write(")()")
        elif node.block_type == BuildBlockExpr.BUILD_GEN:
            # *: 生成器构建块，生成生成器表达式
            self._write("(")
            self._write("(x for x in (")
            self.indent += 1
            for stmt in node.body:
                stmt_kind = getattr(stmt, 'kind', None)
                if stmt_kind == 'ReturnStmt':
                    self._visit(stmt)
                elif isinstance(stmt, (BinOp, UnaryOp, Call, Name, Constant)):
                    self._write(self._expr_to_str(stmt) + ",")
                else:
                    self._visit(stmt)
            self.indent -= 1
            self._write("))")
            self._write(")")

    def _visit_TraitDef(self, node: TraitDef) -> None:
        self._write(f"class {node.name}:")
        self.indent += 1
        for method in node.methods:
            if isinstance(method, FuncDef):
                params_str = ", ".join(p.name for p in method.params)
                if params_str:
                    params_str = f"self, {params_str}"
                else:
                    params_str = "self"
                return_type = f" -> {self._type_to_str(method.return_type)}" if method.return_type else ""
                self._write(f"def {method.name}({params_str}){return_type}: ...")
        self.indent -= 1
        self._write("")

    def _visit_ImplStmt(self, node: ImplStmt) -> None:
        for_type = self._type_to_str(node.for_type) if isinstance(node.for_type, ASTNode) else str(node.for_type)
        self._write(f"# impl {node.trait_name} for {for_type}")
        self.indent += 1
        for method in node.methods:
            if isinstance(method, FuncDef):
                self._visit(method)
        self.indent -= 1
        self._write("")

    def _visit_MetaBlock(self, node: MetaBlock) -> None:
        """生成元编程块的 Cython 代码"""
        self._write(f"# meta block: {node.name}")
        self.indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self.indent -= 1
        self._write("")

    def _visit_LambdaExpr(self, node: Any) -> str:
        """生成 lambda 表达式的 Cython 代码"""
        params = []
        for param in node.params:
            if param.type_annotation:
                params.append(f"{param.name}: {self._type_to_str(param.type_annotation)}")
            else:
                params.append(param.name)
        params_str = ", ".join(params)
        return f"lambda {params_str}: {self._expr_to_str(node.body)}"

    def _visit_TryStmt(self, node: Any) -> None:
        """生成 try/except/finally 语句的 Cython 代码"""
        self._write("try:")
        self.indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self.indent -= 1
        
        # 处理 except 子句
        for except_clause in getattr(node, 'except_clauses', []):
            except_type = self._type_to_str(except_clause.type) if except_clause.type else ""
            except_var = f" as {except_clause.name}" if getattr(except_clause, 'name', None) else ""
            self._write(f"except {except_type}{except_var}:")
            self.indent += 1
            for stmt in except_clause.body:
                self._visit(stmt)
            self.indent -= 1
        
        # 处理 finally 子句
        if hasattr(node, 'finally_body') and node.finally_body:
            self._write("finally:")
            self.indent += 1
            for stmt in node.finally_body:
                self._visit(stmt)
            self.indent -= 1

    def _visit_RaiseStmt(self, node: Any) -> None:
        """生成 raise 语句的 Cython 代码"""
        if node.exc:
            self._write(f"raise {self._expr_to_str(node.exc)}")
        else:
            self._write("raise")

    def _visit_AssertStmt(self, node: Any) -> None:
        """生成 assert 语句的 Cython 代码"""
        if node.msg:
            self._write(f"assert {self._expr_to_str(node.test)}, {self._expr_to_str(node.msg)}")
        else:
            self._write(f"assert {self._expr_to_str(node.test)}")

    def _visit_YieldStmt(self, node: Any) -> None:
        """生成 yield 语句的 Cython 代码"""
        if node.is_from and node.value:
            self._write(f"yield from {self._expr_to_str(node.value)}")
        elif node.value:
            self._write(f"yield {self._expr_to_str(node.value)}")
        else:
            self._write("yield")

    def _visit_SpawnStmt(self, node: Any) -> None:
        """生成 spawn 语句的 Cython 代码"""
        if hasattr(node, 'expr') and node.expr:
            # 使用 Python threading 模块实现并发
            self._write(f"import threading")
            self._write(f"threading.Thread(target=lambda: {self._expr_to_str(node.expr)}).start()")

    def _visit_GoStmt(self, node: Any) -> None:
        """生成 go 语句的 Cython 代码"""
        if hasattr(node, 'expr') and node.expr:
            # 使用 Python threading 模块实现协程
            self._write(f"import threading")
            self._write(f"threading.Thread(target=lambda: {self._expr_to_str(node.expr)}).start()")

    def _visit_Pattern(self, node: Any) -> str:
        """生成模式绑定的 Cython 代码"""
        return node.name

    def _visit_TypeAlias(self, node: Any) -> None:
        """生成类型别名的 Cython 代码"""
        target_type = self._type_to_str(node.target)
        self._write(f"{node.name} = {target_type}")
        self._write("")

    def _visit_BinOp(self, node: BinOp) -> str:
        return f"{self._expr_to_str(node.left)} {node.op} {self._expr_to_str(node.right)}"

    def _visit_UnaryOp(self, node: UnaryOp) -> str:
        return f"{node.op}{self._expr_to_str(node.operand)}"

    def _visit_DerefExpr(self, node: DerefExpr) -> str:
        return f"{self._expr_to_str(node.operand)}[0]"

    def _visit_CastExpr(self, node: CastExpr) -> str:
        """生成类型转换表达式的 Cython 代码"""
        value_str = self._expr_to_str(node.value)
        target_type_str = self._type_to_str(node.target_type)
        
        # 检查是否需要调用 __cast__ 或 __try_cast__
        # 对于基本类型，使用 Cython 的类型转换语法
        basic_types = {'int', 'float', 'double', 'bool', 'str'}
        
        if hasattr(node.value, 'kind') and node.value.kind == 'Name':
            # 如果是变量名，检查是否有 __cast__ 方法
            var_name = node.value.id
            # 在实际实现中，这里应该查询类型系统来确定是否有 __cast__ 方法
            # 简化实现：对于自定义类型，生成 __cast__ 调用
            if target_type_str not in basic_types:
                return f"{value_str}.__cast__[{target_type_str}]()"
        
        # 基本类型转换：使用 Cython 的类型转换语法
        return f"<{target_type_str}>{value_str}"

    def _visit_Call(self, node: Call) -> str:
        if hasattr(node.func, 'id'):
            func_name = node.func.id
            args = ", ".join(self._expr_to_str(arg) for arg in node.args)
            
            # 特殊处理内置函数
            if func_name == 'malloc':
                # malloc 返回 void*，需要类型转换
                return f"<void*>{func_name}({args})"
            elif func_name == 'sizeof':
                # sizeof 需要特殊处理，参数可能是类型或表达式
                return f"{func_name}({args})"
            elif func_name == 'addr':
                # addr(var) 转换为 &var
                if node.args:
                    return f"&{self._expr_to_str(node.args[0])}"
                return f"{func_name}({args})"
            elif func_name == 'free':
                return f"{func_name}({args})"
        
        args = ", ".join(self._expr_to_str(arg) for arg in node.args)
        
        # 如果有调用时的 checker，在调用前调用 checker
        # 使用逗号表达式：(checker(), func(args))[1] 获取函数调用结果
        if node.checker:
            return f"({node.checker}(), {self._expr_to_str(node.func)}({args}))[1]"
        
        return f"{self._expr_to_str(node.func)}({args})"

    def _visit_Name(self, node: Name) -> str:
        return node.id

    def _visit_Constant(self, node: Constant) -> str:
        if isinstance(node.value, str):
            # 检查是否是 f-string
            prefix = getattr(node, 'prefix', None)
            if prefix == 'f':
                return f'f{repr(node.value)}'
            # 使用 repr() 正确处理转义字符
            return repr(node.value)
        if isinstance(node.value, list):
            # 列表字面量：递归访问每个元素
            elements = []
            for item in node.value:
                if isinstance(item, ASTNode):
                    elements.append(self._expr_to_str(item))
                else:
                    elements.append(repr(item))
            return f"[{', '.join(elements)}]"
        return repr(node.value)

    def _visit_StructLiteral(self, node: Any) -> str:
        """生成结构体字面量的 Cython 代码 - StructName {field1: value1, field2: value2}"""
        fields_str = ", ".join(f"{name}={self._expr_to_str(value)}" for name, value in node.fields)
        return f"{node.struct_name}({fields_str})"

    def _visit_Attribute(self, node: Any) -> str:
        return f"{self._expr_to_str(node.value)}.{node.attr}"

    def _visit_Subscript(self, node: Any) -> str:
        return f"{self._expr_to_str(node.value)}[{self._expr_to_str(node.slice)}]"

    def _visit_PointerType(self, node: PointerType) -> str:
        base_type = self._type_to_str(node.base_type)
        return f"{base_type}*"

    def _visit_GenericType(self, node: GenericType) -> str:
        args = ", ".join(self._type_to_str(arg) for arg in node.args)
        return f"{node.name}[{args}]"

    def _expr_to_str(self, node: ASTNode) -> str:
        if isinstance(node, BinOp):
            return self._visit_BinOp(node)
        if isinstance(node, UnaryOp):
            return self._visit_UnaryOp(node)
        if isinstance(node, DerefExpr):
            return self._visit_DerefExpr(node)
        if isinstance(node, CastExpr):
            return self._visit_CastExpr(node)
        if isinstance(node, Call):
            return self._visit_Call(node)
        if isinstance(node, Name):
            return self._visit_Name(node)
        if isinstance(node, Constant):
            return self._visit_Constant(node)
        if isinstance(node, Attribute):
            return self._visit_Attribute(node)
        if isinstance(node, Subscript):
            return self._visit_Subscript(node)
        if hasattr(node, "kind") and node.kind == "StructLiteral":
            return self._visit_StructLiteral(node)
        if hasattr(node, "kind") and node.kind == "BuildBlockExpr":
            # 构建块表达式需要特殊处理，直接调用 _visit_BuildBlockExpr
            old_output = self.output
            self.output = []
            old_indent = self.indent
            self.indent = 0
            try:
                self._visit_BuildBlockExpr(node)
                return "".join(self.output)
            finally:
                self.output = old_output
                self.indent = old_indent
        if hasattr(node, "kind") and node.kind == "LambdaExpr":
            return self._visit_LambdaExpr(node)
        if hasattr(node, "kind") and node.kind == "Pattern":
            return self._visit_Pattern(node)
        if hasattr(node, "id"):
            return node.id
        return str(node)

    def _type_to_str(self, node: ASTNode) -> str:
        if isinstance(node, Name):
            return self.type_mapper.to_cython(node.id)
        if isinstance(node, PointerType):
            return self._visit_PointerType(node)
        if isinstance(node, GenericType):
            return self._visit_GenericType(node)
        if hasattr(node, "id"):
            return self.type_mapper.to_cython(node.id)
        return str(node)