from typing import Any, List
from cypyc.parser.parser import (
    ASTNode, Module, FuncDef, LetStmt, ReturnStmt, IfStmt, ForStmt, WhileStmt,
    BinOp, UnaryOp, Call, Name, Constant, Attribute, Subscript, StructDef,
    StructField, EnumDef, EnumVariant, DeferStmt, DerefExpr, PointerType,
    GenericType, TraitDef, ImplStmt, MetaBlock
)
from cypyc.codegen.type_mapper import TypeMapper


class CythonGenerator:
    def __init__(self):
        self.indent = 0
        self.output = []
        self.type_mapper = TypeMapper()
        self.in_cdef_context = False
        self.needs_libc_import = False  # 是否需要导入C标准库

    def generate(self, node: ASTNode) -> str:
        self.output = []
        # 首先检测是否需要C库导入
        self._detect_libc_usage(node)
        self._visit(node)
        return "\n".join(self.output)
    
    def _detect_libc_usage(self, node: ASTNode) -> None:
        """检测代码中是否使用了需要C标准库的函数"""
        if isinstance(node, Call) and hasattr(node.func, 'id'):
            if node.func.id in ('malloc', 'free', 'sizeof', 'addr'):
                self.needs_libc_import = True
        for attr in dir(node):
            if not attr.startswith("_"):
                value = getattr(node, attr)
                if isinstance(value, ASTNode):
                    self._detect_libc_usage(value)
                elif isinstance(value, list):
                    for item in value:
                        if isinstance(item, ASTNode):
                            self._detect_libc_usage(item)

    def _visit(self, node: ASTNode) -> None:
        method = f"_visit_{node.kind}"
        if hasattr(self, method):
            getattr(self, method)(node)
        else:
            self._visit_children(node)

    def _visit_children(self, node: ASTNode) -> None:
        for attr in dir(node):
            if not attr.startswith("_"):
                value = getattr(node, attr)
                if isinstance(value, ASTNode):
                    self._visit(value)
                elif isinstance(value, list):
                    for item in value:
                        if isinstance(item, ASTNode):
                            self._visit(item)

    def _write(self, text: str) -> None:
        if text:
            self.output.append("    " * self.indent + text)

    def _visit_Module(self, node: Module) -> None:
        self._write("# Generated by Cypy compiler")
        self._write("")
        
        # 添加C标准库导入
        if self.needs_libc_import:
            # sizeof是Cython内置关键字，不需要导入
            self._write("from libc.stdlib cimport malloc, free")
            self._write("")
        
        for stmt in node.body:
            self._visit(stmt)

    def _visit_FuncDef(self, node: FuncDef) -> None:
        has_type_annotation = any(p.type_annotation for p in node.params) or node.return_type
        
        if has_type_annotation:
            return_type = ""
            if node.return_type:
                return_type = f" {self._type_to_str(node.return_type)}"
            
            params = []
            for param in node.params:
                param_str = param.name
                if param.type_annotation:
                    param_str = f"{self._type_to_str(param.type_annotation)} {param.name}"
                params.append(param_str)
            
            self._write(f"cdef{return_type} {node.name}({', '.join(params)}):")
        else:
            self._write(f"def {node.name}():")
        
        self.indent += 1
        
        # 分离defer语句和普通语句
        defer_stmts = []
        normal_stmts = []
        
        for stmt in node.body:
            if isinstance(stmt, DeferStmt):
                defer_stmts.append(stmt)
            else:
                normal_stmts.append(stmt)
        
        # 检查是否有defer语句
        if defer_stmts:
            # 生成try块
            self._write("try:")
            self.indent += 1
            for stmt in normal_stmts:
                self._visit(stmt)
            self.indent -= 1
            
            # 生成finally块（defer语句按逆序执行）
            self._write("finally:")
            self.indent += 1
            # defer语句按声明顺序的逆序执行
            for defer_stmt in reversed(defer_stmts):
                for stmt in defer_stmt.body:
                    # defer body中可能包含表达式节点（如Call），需要转换为表达式语句
                    if isinstance(stmt, (Call, BinOp, UnaryOp, Name, Constant)):
                        self._write(self._expr_to_str(stmt))
                    else:
                        self._visit(stmt)
            self.indent -= 1
        else:
            # 没有defer语句，直接输出所有语句
            for stmt in node.body:
                self._visit(stmt)
        
        self.indent -= 1
        self._write("")

    def _visit_LetStmt(self, node: LetStmt) -> None:
        if node.type_annotation:
            cdef_type = self._type_to_str(node.type_annotation)
            if node.value:
                self._write(f"cdef {cdef_type} {node.name} = {self._expr_to_str(node.value)}")
            else:
                self._write(f"cdef {cdef_type} {node.name}")
        else:
            if node.value:
                self._write(f"{node.name} = {self._expr_to_str(node.value)}")
            else:
                self._write(f"{node.name}")

    def _visit_ReturnStmt(self, node: ReturnStmt) -> None:
        if node.value:
            self._write(f"return {self._expr_to_str(node.value)}")
        else:
            self._write("return")

    def _visit_IfStmt(self, node: IfStmt) -> None:
        self._write(f"if {self._expr_to_str(node.test)}:")
        self.indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self.indent -= 1
        if node.orelse:
            self._write("else:")
            self.indent += 1
            for stmt in node.orelse:
                self._visit(stmt)
            self.indent -= 1

    def _visit_ForStmt(self, node: ForStmt) -> None:
        self._write(f"for {self._expr_to_str(node.target)} in {self._expr_to_str(node.iter)}:")
        self.indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self.indent -= 1

    def _visit_WhileStmt(self, node: WhileStmt) -> None:
        self._write(f"while {self._expr_to_str(node.test)}:")
        self.indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self.indent -= 1

    def _visit_BreakStmt(self, node: Any) -> None:
        self._write("break")

    def _visit_ContinueStmt(self, node: Any) -> None:
        self._write("continue")

    def _visit_ExprStmt(self, node: Any) -> None:
        self._write(self._expr_to_str(node.value))

    def _visit_Assign(self, node: Any) -> None:
        target = self._expr_to_str(node.target)
        value = self._expr_to_str(node.value)
        self._write(f"{target} = {value}")

    def _visit_StructDef(self, node: StructDef) -> None:
        self._write(f"cdef struct {node.name}:")
        self.indent += 1
        for field in node.fields:
            if isinstance(field, StructField):
                field_type = self._type_to_str(field.type_annotation) if field.type_annotation else "object"
                self._write(f"cdef {field_type} {field.name}")
        self.indent -= 1
        self._write("")

    def _visit_StructField(self, node: StructField) -> None:
        pass

    def _visit_EnumDef(self, node: EnumDef) -> None:
        self._write("from enum import IntEnum")
        self._write("")
        self._write(f"class {node.name}(IntEnum):")
        self.indent += 1
        for variant in node.variants:
            if isinstance(variant, EnumVariant):
                if variant.value is not None:
                    self._write(f"{variant.name} = {self._expr_to_str(variant.value)}")
                else:
                    self._write(f"{variant.name}")
        self.indent -= 1
        self._write("")

    def _visit_EnumVariant(self, node: EnumVariant) -> None:
        pass

    def _visit_TraitDef(self, node: TraitDef) -> None:
        self._write(f"class {node.name}:")
        self.indent += 1
        for method in node.methods:
            if isinstance(method, FuncDef):
                params_str = ", ".join(p.name for p in method.params)
                if params_str:
                    params_str = f"self, {params_str}"
                else:
                    params_str = "self"
                return_type = f" -> {self._type_to_str(method.return_type)}" if method.return_type else ""
                self._write(f"def {method.name}({params_str}){return_type}: ...")
        self.indent -= 1
        self._write("")

    def _visit_ImplStmt(self, node: ImplStmt) -> None:
        for_type = self._type_to_str(node.for_type) if isinstance(node.for_type, ASTNode) else str(node.for_type)
        self._write(f"# impl {node.trait_name} for {for_type}")
        self.indent += 1
        for method in node.methods:
            if isinstance(method, FuncDef):
                self._visit(method)
        self.indent -= 1
        self._write("")

    def _visit_MetaBlock(self, node: MetaBlock) -> None:
        pass

    def _visit_BinOp(self, node: BinOp) -> str:
        return f"{self._expr_to_str(node.left)} {node.op} {self._expr_to_str(node.right)}"

    def _visit_UnaryOp(self, node: UnaryOp) -> str:
        return f"{node.op}{self._expr_to_str(node.operand)}"

    def _visit_DerefExpr(self, node: DerefExpr) -> str:
        return f"{self._expr_to_str(node.operand)}[0]"

    def _visit_Call(self, node: Call) -> str:
        if hasattr(node.func, 'id'):
            func_name = node.func.id
            args = ", ".join(self._expr_to_str(arg) for arg in node.args)
            
            # 特殊处理内置函数
            if func_name == 'malloc':
                # malloc 返回 void*，需要类型转换
                return f"<void*>{func_name}({args})"
            elif func_name == 'sizeof':
                # sizeof 需要特殊处理，参数可能是类型或表达式
                return f"{func_name}({args})"
            elif func_name == 'addr':
                # addr(var) 转换为 &var
                if node.args:
                    return f"&{self._expr_to_str(node.args[0])}"
                return f"{func_name}({args})"
            elif func_name == 'free':
                return f"{func_name}({args})"
        
        args = ", ".join(self._expr_to_str(arg) for arg in node.args)
        return f"{self._expr_to_str(node.func)}({args})"

    def _visit_Name(self, node: Name) -> str:
        return node.id

    def _visit_Constant(self, node: Constant) -> str:
        if isinstance(node.value, str):
            return f'"{node.value}"'
        return repr(node.value)

    def _visit_Attribute(self, node: Any) -> str:
        return f"{self._expr_to_str(node.value)}.{node.attr}"

    def _visit_Subscript(self, node: Any) -> str:
        return f"{self._expr_to_str(node.value)}[{self._expr_to_str(node.slice)}]"

    def _visit_PointerType(self, node: PointerType) -> str:
        base_type = self._type_to_str(node.base_type)
        return f"{base_type}*"

    def _visit_GenericType(self, node: GenericType) -> str:
        args = ", ".join(self._type_to_str(arg) for arg in node.args)
        return f"{node.name}[{args}]"

    def _expr_to_str(self, node: ASTNode) -> str:
        if isinstance(node, BinOp):
            return self._visit_BinOp(node)
        if isinstance(node, UnaryOp):
            return self._visit_UnaryOp(node)
        if isinstance(node, DerefExpr):
            return self._visit_DerefExpr(node)
        if isinstance(node, Call):
            return self._visit_Call(node)
        if isinstance(node, Name):
            return self._visit_Name(node)
        if isinstance(node, Constant):
            return self._visit_Constant(node)
        if isinstance(node, Attribute):
            return self._visit_Attribute(node)
        if isinstance(node, Subscript):
            return self._visit_Subscript(node)
        if hasattr(node, "id"):
            return node.id
        return str(node)

    def _type_to_str(self, node: ASTNode) -> str:
        if isinstance(node, Name):
            return self.type_mapper.to_cython(node.id)
        if isinstance(node, PointerType):
            return self._visit_PointerType(node)
        if isinstance(node, GenericType):
            return self._visit_GenericType(node)
        if hasattr(node, "id"):
            return self.type_mapper.to_cython(node.id)
        return str(node)