# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: initializedcheck=False
# cython: nonecheck=False
# cython: warn.unreachable=False
# cython: warn.undeclared=False
# Generated by Cypy compiler
"""
Cython module compiled from Cypy source
Source file: unknown
"""
import cython
from libc.stdlib cimport malloc, free
from libc.string cimport memset
import datetime as _cypy_dt
__generated_at__ = _cypy_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
__module_version__ = '1.0.0'
__name__ = "unknown"
__file__ = ""
__package__ = ""
__path__ = None
__compile_time__ = "2026-09-28T10:51:40"
__target__ = "AMD64-windows"
__profile__ = "debug"
__all__ = ["add_values", "main"]
__private__ = []
__deps__ = []
def add_values(a, b, c):
    return a + b + c
def main():
    x: int = 10
    y: int = 20
    c: int = 30
    result: int = add_values(x, y, c=c)
    print(result)
    return 0